# Generated by Django 5.0.7 on 2024-07-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/banner_imgs')),
                ('Discount_deal', models.CharField(max_length=100)),
                ('Sale', models.IntegerField()),
                ('Quote', models.CharField(max_length=200)),
                ('Discount', models.IntegerField()),
            ],
        ),
    ]
