# Generated by Django 5.0.7 on 2024-07-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_banner_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner_area',
            name='Sale',
        ),
    ]
