# Generated by Django 5.0.7 on 2024-07-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_banner_area_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner_area',
            name='Link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='Link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
