# Generated by Django 5.0.7 on 2024-07-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_product_product_information_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_image',
            name='image_url',
            field=models.ImageField(upload_to='product_images/'),
        ),
        migrations.AlterModelTable(
            name='product',
            table='app_Product',
        ),
    ]
