# Generated by Django 5.0.7 on 2024-07-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_product_image_image_url_alter_product_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_image',
            name='image_url',
            field=models.CharField(max_length=100),
        ),
    ]
