# Generated by Django 5.0.7 on 2024-07-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_coupon_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner_area_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/banner_imgs')),
                ('Discount_deal', models.CharField(max_length=100)),
                ('Quote', models.CharField(max_length=200)),
                ('Discount', models.IntegerField()),
                ('Link', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
