# Generated by Django 5.0.7 on 2024-07-27 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_product_featured_products_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured_products_section',
        ),
    ]
